let listaCompra = ["jamón", "queso", "pan", "arroz", "pasta", "tomate", "plátano"]
let cards= [{
    titulo: "Mediterráneo",
    imagen: "./imagenes/mediterraneo.jpg",
    pais: "España",
    ano: "2021",
    tipo: "Drama",
    sinopsis: "Otoño de 2015. Dos socorristas, Óscar y Gerard, viajan hasta la isla de Lesbos, en Grecia,impactados por la fotografía de un niño ahogado en las aguas del Mediterráneo. Al llegar descubren una realidad sobrecogedora. Miles de personas arriesgan sus vidas cada día cruzando el mar en precarias embarcaciones y huyendo de conflictos armados. Sin embargo, nadie ejerce labores de rescate. Junto a Esther, Nico y otros miembros del equipo, lucharán por cumplir un cometido, dando apoyo a personas que lo necesitan. Para todos ellos, este viaje inicial supondrá una odisea que marcará sus vidas."
},
{
    titulo:"Alcarràs", 
    imagen: "./imagenes/alcarras.jpeg" ,
    pais: "España" ,
    ano: "2022",
    tipo: "Drama",
    sinopsis:"'Alcarràs' puede leerse desde muchos puntos de vista: como la reivindicación de la identidad de un oficio, el del campesinado tradicional, que se identifica con la tierra y sus frutos; como el retrato orgánico y vivaz, exento de maniqueísmos, de la crisis de una familia provocado por un dilema moral; como una reflexión sobre cómo el progreso borra los rastros de la Historia; en fin, sobre un trozo de vida que late y respira a través de los rostros de actores no profesionales que parecen protagonizar el documental de un verano que les depara un futuro incierto",
},
{
    titulo: "Espíritu sagrado",
    imagen: "./imagenes/espiritu-sagrado.jpg",
    pais: "España"  ,
    ano: "2021",
    tipo: "Drama",
    sinopsis:"El menú podría saber a refrito posmoderno si no fuera por la familiaridad con la que García Ibarra se mueve por su Elche natal, construyendo un himno tan irreverente como sentido al barrio obrero de Carrús. Si fuera posible imbricar con artes alquímicas los humores profanos de Aki Kaurismäki, Luis Buñuel y Roy Andersson, el resultado podría parecerse bastante a este 'Espíritu sagrado",

},
{   titulo: "Maixabel",
    imagen: "./imagenes/maixabel.jpg",
    pais: "España"  ,
    ano: "2021",
    tipo: "Drama",
    sinopsis: "La propuesta de la cinta de propiciar encuentros entre víctimas y asesinos no parece fácil de asimilar en principio, aunque está avalada por la realidad, ya que su principal promotora ha sido Maixabel Lasa, viuda del político asesinado Juan María Jáuregui. El guion, espléndido, coescrito por la cineasta con Isa Campo, se adentra en los personajes mostrando cómo evolucionan en sus sentimientos y en su modo de pensar y actuar. Un objetivo que se logra gracias al trabajo sobresaliente de Blanca Portillo, Luis Tosar y Urko Olazabal. La cinta, que avanza sin estridencias, llega a provocar una emoción profunda con su sencillez, sin excesos fáciles. Bollaín demuestra un dominio magistral de su oficio en la que es su película más redonda",
},
{   titulo: "El buen patrón",
    imagen: "./imagenes/el-buen-patron.jpg",
    pais: "España" ,
    ano: "2021",
    tipo: "Drama",
    sinopsis: "Como si se tratara de un inmenso contracampo (eso sí, rodado casi 20 años después) de Los lunes al sol (2002), en 'El buen patrón' Fernando León de Aranoa nos propone indagar en la mentalidad de la otra parte del mundo laboral, en este caso, el dueño de una fábrica de mediano tamaño, hombre previsiblemente formado (es ingeniero), todavía de buen ver y, viene casi en el lote, con modos de macho alfa. Ese hombre, Blanco (mediante el que Bardem nos brinda uno de sus trabajos más deslumbrantes: él es, sencillamente, la película), tiene un problema: ha de actuar casi a contratiempo para que su deseo, ser recompensado con un premio empresarial, no se vea manchado por pequeños detalles de última hora que, en realidad, son los gestos que explican toda una vida",
},
{    
    titulo: "Las niñas",
    imagen: "./imagenes/las-ninas.jpg",
    pais: "España" ,
    ano: "2021",
    tipo: "Drama",
    sinopsis:"Palomero hace avanzar la trama a partir de un impresionante trabajo de su elenco infantil, un prodigio de naturalidad. Y poco a poco, lo que se va abriendo paso no es solo la contradicción entre una España tradicional, representada por la familia del pueblo y el ambiente del colegio religioso, y una en vías de rápido cambio, sino también una sospecha abyecta (quién es realmente el padre de la niña), sobre la que la directora no se pronuncia, pero a la cual deja abierta la puerta para que mentes retorcidas, como la mía, busquen respuesta",
},
{   titulo: "Campeones",
    imagen: "./imagenes/campeones.jpg",
    pais: "España" ,
    ano: "2021",
    tipo: "Drama",
    sinopsis: "Jugamos para ganar, no para humillar, le responde alguien a Marcos, entrenador de baloncesto condenado a hacerse cargo de un equipo de discapacitados intelectuales, cuando grita a sus variopintos jugadores: ¡A machacarlos! Seis palabras que definen el tono de la nueva película de Javier Fesser, la mejor de su filmografía, en la que se reivindica, sin esas prédicas ni provocaciones tan habituales en nuestro cine, la gloriosa diferencia que hace único a cada ser humano",
}
]